apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: photogenic
  name: photogenic
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 31200
  selector:
    app: photogenic
  type: LoadBalancer
status:
  loadBalancer: {}
