apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: photogenic
  name: photogenic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: photogenic
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: photogenic
    spec:
      containers:
      - image: rispajoseph/devops-project
        name: devops-project
        ports:
        - containerPort: 80
        resources: {}
status: {}
